print("The / operator does 'normal' float division:")
print(" 5/3  =", (5 / 3))
print()
print("The // operator does integer division:")
print(" 5//3 =", (5 // 3))
print(" 2//3 =", (2 // 3))
print(" -1//3 =", (-1 // 3))
print(" -4//3 =", (-4 // 3))
